name: Run Chore Management Script

on:
  schedule:
    - cron: '0 19 * * 0'
    - cron: '0 19 * * 1'
  workflow_dispatch:

jobs:
  run-chore-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Needed for push access

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run script
      working-directory: ./src
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: python main.py --prod

    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add ./src/roommate_to_chore.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update chore assignments [skip ci]" && git push)